name: "Hello Actions1"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Sharon"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "pink"